apiVersion: v1
kind: Endpoints
metadata:
  name: my-endpoints-service
subsets:
  - addresses:
      - ip: 10.244.2.54 # apache
      - ip: 10.244.2.53 # nginx
    ports: 
      - port: 80
---

apiVersion: v1
kind: Service
metadata:
  name: my-endpoints-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80