apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
  labels:
    type: web-app
spec:
  containers:
  - name: apache-container
    image: httpd
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits: 
        cpu: "1000m"
        memory: "256Mi"
  - name: nginx-container
    image: nginx
    resources:
      requests:
        cpu: "400m"
        memory: "128Mi"
      limits: 
        cpu: "1100m"
        memory: "356Mi"
